name: Gridtestml
favicon: null
layout_spectrum: 0.5019746776670218
typography_spectrum: 0.6327231882605702
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8498339247889817
  lightness: 0.9920562410261482
  saturation: 0.969713008031249
  rhythmicContrast: 0.8112556810956448
purpose: []
